### ISSUE TITLE
Patcher: Make detection of Steam SADX less strict

### ISSUE THREAD

**Issue by cheatfreak47** [cheatfreak47/BetterSADX-bits#1]
It's been a known issue for a while that some people have issues with the install detection on the patcher- so maybe we should remove the harsh check for the uninstall path we've been using thus far.

Instead we should probably just pull the game path from uninstall if possible, otherwise, we prompt the user to locate their SADX Install Folder and run the patch. We should also check for a steam version file if we can, just to make sure the patch doesn't attempt an install willy-nilly.

We'll have to discuss how to approach this further sometime.

**Comment by Carlmundo** [comment]
Fixed for 4.1
