### ISSUE TITLE
Hotpatch OR BetterSADX Uninstaller

### ISSUE THREAD

**Issue by cheatfreak47** [cheatfreak47/BetterSADX-bits#11]
We need to make a hotpatch for updating from 4.0 to 4.1 once we have 4.1 Beta ready- before we can release it.

Shouldn't be too difficult.

**Comment by cheatfreak47** [comment]
Might make an uninstaller instead that backs up user save data and have the standard installer restore it from the backup if it exists.

**Comment by Carlmundo** [comment]
Fixed by removing redundant 4.0 folders during install.
