### ISSUE TITLE
Speedrun Build Changes

### ISSUE THREAD

**Issue by cheatfreak47** [cheatfreak47/BetterSADX-bits#14]
Reported by Shanekilz- there's apparently an inconsistent issue involving the cannon at the end of act 1. 
https://puu.sh/tYPwA/9e573b09b6.mp4

Will attempt to reproduce myself, but for now that video demonstrates the issue.

Possible Causes:

- Mod Loader being newer (most likely culprit)
- Steam hooking the game (???)
- the d3d9 wrapper (doubtful)
- frame limiter (doubtful)
- user processor affinity 
- user operating system

4.1 todo:
~~- verifiy integrity of all of the skydeck related files before next release~~
- remove d3d9 wrapper from minimal install entirely (d3d8.dll in install folder root)
- include xinput-fix as the default input setting, but input mod will be included but disabled
- disable framelimiter by default- not everyone needs that turned on- only those with the overactive framerate issue

**Comment by cheatfreak47** [comment]
https://www.speedrun.com/patches/xinputv2_SwbaL.zip you'll  you'll need this for the 4.1 todo list

**Comment by Carlmundo** [comment]
https://github.com/Carlmundo/BetterSADX/commit/fc2e76845504f97fb4e4477916704db4f355aa48
Just need you to make the ini file with frame limiter disabled.
