### ISSUE TITLE
Update SADXFE

### ISSUE THREAD

**Issue by cheatfreak47** [cheatfreak47/BetterSADX-bits#16]
SADXFE is now a single mod, here is the latest release as a zip file for the mods folder.
[SADXFE.zip](https://github.com/cheatfreak47/BetterSADX-bits/files/1023990/SADXFE.zip)

**Comment by Carlmundo** [comment]
Done - https://github.com/Carlmundo/BetterSADX/commit/1f3267f058f704c7750f6e98279c80e710571f89
