### ISSUE TITLE
Ongoing Changes to MimicDCTextures

### ISSUE THREAD

**Issue by Z0rakaroZ** [cheatfreak47/BetterSADX-bits#19]
### v1.2.0
[MimicDCTextures.zip](https://github.com/cheatfreak47/BetterSADX-bits/files/2699523/MimicDCTextures.zip)
![mdct-1 1 9-vs-1 2 0](https://user-images.githubusercontent.com/45943617/50291729-5d84a100-043d-11e9-83d1-4fe9a5b32636.jpg)
- Better quality Metal Sonic from Gamecube.
- Hi-res head and body textures for Tails and Amy.
- Fixed ear issues with Tails, Amy, and Super Sonic.
- Matched contrast on Super Sonic's belly texture.
- Reduced mod size from 2.05 MB to 1.54 MB by optimizing all textures.

Merry Kwanzchrismahanukkahmas! The stockings were hung by the chimney.

**Comment by cheatfreak47** [comment]
Updated, and happy holidays to you too

**Comment by Z0rakaroZ** [comment]
Thanks a bunch for adding the updates. There's just one more, _very_ last update that I made. Since it's the 20th Anniversary of Sonic Adventure, I thought about improving Sonic's shoes. They were the last textures that lacked Dreamcast textures. Not to mention its textures were noticeable jagged. Now they should look closer to the original textures. Cheerios!

### v1.2.1
[MimicDCTextures.zip](https://github.com/cheatfreak47/BetterSADX-bits/files/2706620/MimicDCTextures.zip)
![120vs121](https://user-images.githubusercontent.com/45943617/50390337-1e3ba600-0704-11e9-963a-e3b72639843a.jpg)
-Dreamcast shoes' textures for Sonic and Super Sonic.

**Comment by cheatfreak47** [comment]
Updated!

**Comment by Z0rakaroZ** [comment]
meh... Sorry to be a bumper, but I couldn't help noticing the colors of Metal Sonic during my full playthrough. His body looks like a shade of neon-blue sporting in tomato shoes. Here's an update that turns Metal Sonic's colors accurate to his original colors with scanlines on his red eyes, along with a minor adjustment for the light speed shoes. In case you're wondering about the red/white gradient, more gradient looks too dark on DX shoes. Better we leave the gradient shade alone. Hope this'll cheer people up in the upcoming new year holiday.

### v1.2.2
[MimicDCTextures.zip](https://github.com/cheatfreak47/BetterSADX-bits/files/2717613/MimicDCTextures.zip)
![metalupdate](https://user-images.githubusercontent.com/45943617/50552648-bfc37a00-0c65-11e9-84ea-6c63f066c970.jpg)
-Improved the colors of Metal Sonic.
-Minor improvement for the light speed shoes.

**Comment by cheatfreak47** [comment]
I'm gonna have to reject the scanlines on metal sonic's eyes, but the rest is OK, wanna reupload without that? The change is a bit to radical I think.

Edit: Eh, nevermind, I guess it's fine, most people won't mind anyway. Updating now.

**Comment by Z0rakaroZ** [comment]
Nah, I had a feeling they came out too thick. He has them but they're supposed to be thinner and harder to notice. How's this look? I reduced it.

### Old (gamecube) vs 1.2.2 vs new
![old gamecube](https://user-images.githubusercontent.com/45943617/50565089-4f663880-0cf9-11e9-9a60-b3bea0c3d26f.png)
![1 2 2](https://user-images.githubusercontent.com/45943617/50565090-50976580-0cf9-11e9-8d61-5ab41255df05.png)
![new](https://user-images.githubusercontent.com/45943617/50577748-d3edaf80-0dfc-11e9-81e5-a6c9bf37f894.png)

1.2.2 vs new
![50565102-5db45480-0cf9-11e9-84a0-fa6defe5fa29](https://user-images.githubusercontent.com/45943617/50577754-e9fb7000-0dfc-11e9-8de5-6af91bace32e.png)

Edit: further improved the eye texture, images updated.
![50566507-94459b80-0d08-11e9-8dcf-dbaa9ab5d0af](https://user-images.githubusercontent.com/45943617/50577735-9f79f380-0dfc-11e9-93a4-f3c31a194ab1.png)

+Included Big's finger textures -(not including the palm texture due to a mirror bug)-
+Tails' dreamcast jet anklet texture.
And with a little touch of meh-ish gradient on the sides of his anklet. Still better than the old edit.
![50613571-f12d8700-0eab-11e9-8763-045f276cdca8](https://user-images.githubusercontent.com/45943617/50658705-2f887c00-0f68-11e9-8db8-1d81adcd3081.jpg)
![50613571-f12d8700-0eab-11e9-8763-045f276cdca82](https://user-images.githubusercontent.com/45943617/50658708-31523f80-0f68-11e9-88aa-81863cae274b.jpg)
[MimicDCTextures.zip](https://github.com/cheatfreak47/BetterSADX-bits/files/2725142/MimicDCTextures.zip)

Now, if only I can figure out fixing Metal Sonic's standing, landing and idle pose animations. I can swap his running animation in cheat engine- still don't know how to do the dll mod loader config thing.

**Comment by Z0rakaroZ** [comment]
👆🏻 v1.2.3 update is ready for takeoff... no changes made since last week.

**Comment by cheatfreak47** [comment]
Okay, I'll get it out shortly, when I get home
