### ISSUE TITLE
Small changes to some mod stuff

### ISSUE THREAD

**Issue by cheatfreak47** [cheatfreak47/BetterSADX-bits#3]
1. Rename "DC_Edition" folder to "DC_Mods" ✔️ 
1. Remove "DC_CameraAngles" because it's apparently redundant according to PiKeyAr ✔️  Taken care of by 
1. ~~Remove "SUPERSONIC.PVM" from "DC_CharTextures/system" because uuuugly.~~ New texture made for MimicDCTextures
1. ~~Move "DC_CharTextures" out of /DC_Mods/ because it's not a part of the Dreamcast Conversion- but still only include it in the DC component.~ Mod Remade as MimicDCTextures

Most of these will be fixed by #7 for the Dreamcast Edition updates.

**Comment by cheatfreak47** [comment]
more may be added to this list before it can be closed

**Comment by Carlmundo** [comment]
Points 1-4 have been done but won't we need to update the config files?

**Comment by cheatfreak47** [comment]
Yeah, I'll generate new INIs for BetterSADX 4.1 before release.

**Comment by cheatfreak47** [comment]
Done
