### ISSUE TITLE
Patcher: component and edition changes

### ISSUE THREAD

**Issue by cheatfreak47** [cheatfreak47/BetterSADX-bits#6]
1. Move Input-Mod from _minimal_ to _standard_.
1. Make new component _speedrunner_ and have it only install when picking the minimal install
1. Move "CCEF" from _minimal_ into _speedrunner_
1. Add "XInput Fix" we previously removed into the _speedrunner_ component.

the main goal of this is to make the speedrunner install exactly what speedrunners want- only 3 mods:
CCEF, XInput Fix, and Frame Limit.

Turns out CCEF (aka Freecam Fix) is redundant in both "Standard" and "Full" packages because SADXFE actually includes that change. Go figure.

And XInput-Fix is just stupid for the general user as well.

---

I also want to add a install mode called "Strict Conversion (no mods included)" that literally installs no mods at all, it just converts the Steam Port to the Moddable 2004 port.

**Comment by Carlmundo** [comment]
Done - https://github.com/Carlmundo/BetterSADX/commit/fc2e76845504f97fb4e4477916704db4f355aa48
